require:
  - rubocop-inhouse

inherit_gem:
  rubocop-inhouse:
    - config/default.yml

AllCops:
  TargetRubyVersion: 3.1

Metrics/MethodLength:
  CountAsOne: ['array', 'method_call']

Metrics/ClassLength:
  CountAsOne: ['array', 'method_call']
