# frozen_string_literal: true

module Protos
  module Icon
    module Inhouse
      # autogenerated:start
      autoload :Facebook, "protos/icon/inhouse/facebook.rb"
      autoload :Twitter, "protos/icon/inhouse/twitter.rb"
      autoload :Youtube, "protos/icon/inhouse/youtube.rb"
      # autogenerated:finish
    end
  end
end
