# frozen_string_literal: true

module Protos
  module Icon
    module Inhouse
      # autogenerated:start
      autoload :Bold, "protos/icon/inhouse/bold.rb"
      autoload :Facebook, "protos/icon/inhouse/facebook.rb"
      autoload :Github, "protos/icon/inhouse/github.rb"
      autoload :Instagram, "protos/icon/inhouse/instagram.rb"
      autoload :Italic, "protos/icon/inhouse/italic.rb"
      autoload :OrderedList, "protos/icon/inhouse/ordered_list.rb"
      autoload :Quote, "protos/icon/inhouse/quote.rb"
      autoload :Twitter, "protos/icon/inhouse/twitter.rb"
      autoload :Underline, "protos/icon/inhouse/underline.rb"
      autoload :UnorderedList, "protos/icon/inhouse/unordered_list.rb"
      autoload :Youtube, "protos/icon/inhouse/youtube.rb"
      # autogenerated:finish
    end
  end
end
