# frozen_string_literal: true

module Protos
  module Icon
    module Lucide
      # autogenerated:start
      autoload :CirclePile, "protos/icon/lucide/circle_pile.rb"
      autoload :GitBranchMinus, "protos/icon/lucide/git_branch_minus.rb"
      autoload :GitBranchPlus, "protos/icon/lucide/git_branch_plus.rb"
      autoload :GitBranch, "protos/icon/lucide/git_branch.rb"
      autoload :History, "protos/icon/lucide/history.rb"
      autoload :SquareStack, "protos/icon/lucide/square_stack.rb"
      autoload :TestTubeDiagonal, "protos/icon/lucide/test_tube_diagonal.rb"
      # autogenerated:finish
    end
  end
end
