# frozen_string_literal: true

require_relative "helpers"

ROOT_DIR = Pathname.new(__dir__).join("..").freeze
OUTPUT_DIR = ROOT_DIR.join("lib", "protos", "icon", "lucide").freeze

RUBOCOPS = %w[
  Layout/LineLength
].join(", ")

TEMPLATE = ERB.new <<~ERB
  # frozen_string_literal: true

  # This file was generated by the `generators/lucide.rb` generator.

  # rubocop:disable #{RUBOCOPS}
  module Protos
    module Icon
      module Lucide
        class <%= icon_class_name %> < LucideComponent
          def solid
  <%= solid_icon %>
          end
        end
      end
    end
  end
  # rubocop:enable #{RUBOCOPS}
ERB

require "debug"

class ResourcePath
  REGEXP = %r{lucide/24/(?<variant>solid)/(?<name>.+)\.svg}

  attr_reader :variant, :name

  def initialize(path)
    @path = path
    @variant, @name = path.to_s.match(REGEXP).captures
  end

  def icon_class_name
    @name.split("-").map(&:capitalize).join
  end

  def solid?
    @variant == "solid"
  end

  def filename
    @path.basename.to_s.split(".").first.tr("-", "_")
  end

  def read
    File.read(@path)
  end
end

class Resource
  attr_reader :name

  def initialize(name, paths)
    @name = name
    @solid_path = paths.find(&:solid?)
  end

  def file_name
    OUTPUT_DIR.join("#{@solid_path.filename}.rb")
  end

  def relative_file_path
    file_name.relative_path_from(ROOT_DIR.join("lib")).to_s
  end

  def solid_icon
    build_icon(@solid_path)
  end

  private

  def build_icon(path)
    Phlexing::Converter
      .convert(path.read)
      .sub("\n) do", ",\n  **attrs) do")
      .split("\n")
      .map { |line| (" " * 10) + line }
      .join("\n")
  end
end

resource_paths = Pathname
  .glob(ROOT_DIR
  .join("assets/lucide/24/**/*.svg"))
  .map do |path|
    ResourcePath.new(path)
  end

resources = resource_paths
  .group_by(&:icon_class_name)
  .map do |icon_class_name, paths|
    Resource.new(icon_class_name, paths)
  end

module_file = OUTPUT_DIR.join("..", "lucide.rb")
add_autoload_entries(module_file, resources)

resources.with_progress.each do |resource|
  File.write(
    resource.file_name,
    TEMPLATE.result_with_hash(
      {
        icon_class_name: resource.name,
        solid_icon: resource.solid_icon
      }
    )
  )
end
