# frozen_string_literal: true

# This file was generated by the `generators/inhouse.rb` generator.

module Protos
  module Icon
    module Inhouse
      class Italic < Component
        def view_template
          svg(
            **attrs,
            role: "presentation",
            height: "16",
            width: "16",
            aria_hidden: "true",
            xmlns: "http://www.w3.org/2000/svg",
            fill: "none",
            viewbox: "0 0 14 16"
          ) do |s|
            s.path(
              stroke: "currentColor",
              stroke_linecap: "round",
              stroke_linejoin: "round",
              stroke_width: "2",
              d: "m3.874 15 6.143-14M1 15h6.33M6.67 1H13"
            )
          end
        end
      end
    end
  end
end
