# frozen_string_literal: true

# This file was generated by the `generators/inhouse.rb` generator.

# rubocop:disable Layout/LineLength
module Protos
  module Icon
    module Inhouse
      class OrderedList < Component
        def view_template
          svg(
            **attrs,
            role: "presentation",
            height: "16",
            width: "16",
            aria_hidden: "true",
            xmlns: "http://www.w3.org/2000/svg",
            fill: "none",
            viewbox: "0 0 21 18"
          ) do |s|
            s.path(
              stroke: "currentColor",
              stroke_linecap: "round",
              stroke_linejoin: "round",
              stroke_width: "2",
              d:
                "M9.5 3h9.563M9.5 9h9.563M9.5 15h9.563M1.5 13a2 2 0 1 1 3.321 1.5L1.5 17h5m-5-15 2-1v6m-2 0h4"
            )
          end
        end
      end
    end
  end
end
# rubocop:enable Layout/LineLength
