# frozen_string_literal: true

# This file was generated by the `generators/inhouse.rb` generator.

# rubocop:disable Layout/LineLength
module Protos
  module Icon
    module Inhouse
      class Quote < Component
        def view_template
          svg(
            **attrs,
            role: "presentation",
            height: "16",
            width: "16",
            aria_hidden: "true",
            xmlns: "http://www.w3.org/2000/svg",
            fill: "currentColor",
            viewbox: "0 0 18 14"
          ) do |s|
            s.path(
              d:
                "M6 0H2a2 2 0 0 0-2 2v4a2 2 0 0 0 2 2h4v1a3 3 0 0 1-3 3H2a1 1 0 0 0 0 2h1a5.006 5.006 0 0 0 5-5V2a2 2 0 0 0-2-2Zm10 0h-4a2 2 0 0 0-2 2v4a2 2 0 0 0 2 2h4v1a3 3 0 0 1-3 3h-1a1 1 0 0 0 0 2h1a5.006 5.006 0 0 0 5-5V2a2 2 0 0 0-2-2Z"
            )
          end
        end
      end
    end
  end
end
# rubocop:enable Layout/LineLength
