# frozen_string_literal: true

# This file was generated by the `generators/inhouse.rb` generator.

# rubocop:disable Layout/LineLength
module Protos
  module Icon
    module Inhouse
      class Underline < Component
        def view_template
          svg(
            **attrs,
            role: "presentation",
            aria_hidden: "true",
            height: "16",
            width: "16",
            xmlns: "http://www.w3.org/2000/svg",
            fill: "none",
            viewbox: "0 0 16 20"
          ) do |s|
            s.path(
              stroke: "currentColor",
              stroke_linecap: "round",
              stroke_linejoin: "round",
              stroke_width: "2",
              d: "M12 1v9.5a4.5 4.5 0 1 1-9 0V1M1 1h4m5 0h4M1 19h14"
            )
          end
        end
      end
    end
  end
end
# rubocop:enable Layout/LineLength
