# frozen_string_literal: true

# This file was generated by the `generators/lucide.rb` generator.

module Protos
  module Icon
    module Lucide
      class GitBranchMinus < LucideComponent
        def solid
          svg(
            **attrs,
            xmlns: "http://www.w3.org/2000/svg",
            width: "24",
            height: "24",
            viewbox: "0 0 24 24",
            fill: "none",
            stroke: "currentColor",
            stroke_width: "2",
            stroke_linecap: "round",
            stroke_linejoin: "round",
            class: "lucide lucide-git-branch-minus-icon lucide-git-branch-minus"
          ) do |s|
            s.path(d: "M15 6a9 9 0 0 0-9 9V3")
            s.path(d: "M21 18h-6")
            s.circle(cx: "18", cy: "6", r: "3")
            s.circle(cx: "6", cy: "18", r: "3")
          end
        end
      end
    end
  end
end
