# frozen_string_literal: true

# This file was generated by the `generators/lucide.rb` generator.

# rubocop:disable Layout/LineLength
module Protos
  module Icon
    module Lucide
      class Package < LucideComponent
        def solid
          svg(
            xmlns: "http://www.w3.org/2000/svg",
            width: "24",
            height: "24",
            viewbox: "0 0 24 24",
            fill: "none",
            stroke: "currentColor",
            stroke_width: "2",
            stroke_linecap: "round",
            stroke_linejoin: "round",
            class: "lucide lucide-package-icon lucide-package",
            **attrs
          ) do |s|
            s.path(
              d:
                "M11 21.73a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73z"
            )
            s.path(d: "M12 22V12")
            s.polyline(points: "3.29 7 12 12 20.71 7")
            s.path(d: "m7.5 4.27 9 5.15")
          end
        end
      end
    end
  end
end
# rubocop:enable Layout/LineLength
