# frozen_string_literal: true

# This file was generated by the `generators/lucide.rb` generator.

# rubocop:disable Layout/LineLength
module Protos
  module Icon
    module Lucide
      class SquareStack < LucideComponent
        def solid
          svg(
            xmlns: "http://www.w3.org/2000/svg",
            width: "24",
            height: "24",
            viewbox: "0 0 24 24",
            fill: "none",
            stroke: "currentColor",
            stroke_width: "2",
            stroke_linecap: "round",
            stroke_linejoin: "round",
            class: "lucide lucide-square-stack-icon lucide-square-stack",
            **attrs
          ) do |s|
            s.path(d: "M4 10c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h4c1.1 0 2 .9 2 2")
            s.path(d: "M10 16c-1.1 0-2-.9-2-2v-4c0-1.1.9-2 2-2h4c1.1 0 2 .9 2 2")
            s.rect(width: "8", height: "8", x: "14", y: "14", rx: "2")
          end
        end
      end
    end
  end
end
# rubocop:enable Layout/LineLength
