# frozen_string_literal: true

# This file was generated by the `generators/lucide.rb` generator.

# rubocop:disable Layout/LineLength
module Protos
  module Icon
    module Lucide
      class TestTubeDiagonal < LucideComponent
        def solid
          svg(
            **attrs,
            xmlns: "http://www.w3.org/2000/svg",
            width: "24",
            height: "24",
            viewbox: "0 0 24 24",
            fill: "none",
            stroke: "currentColor",
            stroke_width: "2",
            stroke_linecap: "round",
            stroke_linejoin: "round",
            class: "lucide lucide-test-tube-diagonal-icon lucide-test-tube-diagonal"
          ) do |s|
            s.path(
              d: "M21 7 6.82 21.18a2.83 2.83 0 0 1-3.99-.01a2.83 2.83 0 0 1 0-4L17 3"
            )
            s.path(d: "m16 2 6 6")
            s.path(d: "M12 16H4")
          end
        end
      end
    end
  end
end
# rubocop:enable Layout/LineLength
